language: go

go:
  - 1.x

env:
  - GO111MODULE=on

script:
  #  FIXME: add -race flag again after this is solved: https://github.com/privacybydesign/irmago/issues/57
  go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
